### ISSUE TITLE
Mostrar en Opendomo

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#10]
Hola,
Tengo funcionando el Domino de forma contínua más de dos días, no se observa anomalía. La representación web siempre muestra lamisma. Mi siguiente paso será cablear algún interruptor y led para representar cambios. Pero lo que más me extraña es que tanto en la Raspberry como en la máquina virtual con las dos versiones de opendomo no se me muestra el Domino. Es normal?

Saludos

**Comment by Shegar81** [comment]
Acabo de cargar la última versión subida y ahora ya me aparecen en el Opendomo V2 el dispositivo. Si acaso dejemoslo un par de días funcionando y si sigue funcionando se puede dar por cerrado. Aunque de momento solo se muestran los inputs los outputs no. Y solo se muestran no permite asignarlos.

Saludos y felicidades por el gran trabajo que estais realizando.

**Comment by opalenzuela** [comment]
Cerrando este issue.

**Comment by Shegar81** [comment]
Hola,

Reabro el tema ya que me da errores.
No siempre se vé en Opendomo los puertos del Arduino. Pasa tanto en la versión 1 como en la 2 de Opendomo ( no sé si influye que lo haga con máquina virtual, las dos versiones y prueba también con la segunda versión en Raspberry). No siempre aparecen. 

Como segundo dato curioso en caso de representarse solo lo hacen las entradas tanto digitales como analógicas pero no se consiguen ver las salidas, esto no sé si es normal, pero yo recuerdo que en el pasado cuando me funcionó en versión uno y con versiones anteriores de Domino funcionó las entradas y las salidas. Si no es así corrígeme Oriol. 

Os suena algún programa para ver si salen correctamente los mensajes por el puerto adecuado y en formato adecuado?

Saludos

César

**Comment by opalenzuela** [comment]
Una prueba:

¿Podrías mirar si en /var/opendomo/control/ te aparecen todos los puertos correctamente? Tal vez el problema venga por algún caracter inesperado.

Para ver las tramas enviadas en broadcast, lo mejor que se me ocurre es Wireshark.

**Comment by cosmopaco** [comment]
Creo que la pregunta deberia ser. Que formato tienen que tener los mensajes?

**Comment by Shegar81** [comment]
Descargué y ejecuté el Wireshark y observé que el mensaje no es el mismo que emite por el puerto serie. Se transmitía correctamente el isalive pero después a la hora de emitir los puertos solo emitía el nombre del puerto. El tema de estados o cosas por el estilo no me pareció verlo reflejado. En si yo leo dos tipos de mensajes uno que el data contiene 27bytes correspondiente al "***\* isalive" y otro de 17 bytes correspondiente al estado de los puertos. Se me hace extraño que le creo un cambio de puerto y no lo veo reflejado. Creo que no se está transmitiendo correctamente esa información.
Aquí muestro los dos mensajes : 
"ODC02:WTCHDG:devkt isalive"
"ODC02:WTCHDGdi002."

Creo habrá que repasar la parte de transmisión. Como veís el que tengo conectado es el que tiene implementado el Watchdog.

Saludos

**Comment by Shegar81** [comment]
Buenas

Después que el finde pasado estuviera trabajando este he podido dedicar algo de tiempo a hacer pruebas.A ver si me podeis arrojar algo de luz. 
El fallo que comenté de transmisión no sé por que pero solo me pasa en el Arduino con la implementación de Watchdog. Tengo que revisar código en que modifico las cosas para que transmita correcamente. He mirado y por el puerto serie también me da valores erróneos. 
He hecho la misma comprobación pero en el que no tiene Watchdog y ahí la transmisión es la correcta pero por contra sigue sin funcionar. 
Me he dado cuenta que si hay un cambio en alguno de los puertos este no lo emite en ninguno de los "canales", ni serie ni UDP. Tengo que revisar a ver si en el último cambio que se subió se ha normalizado esto. Esto último Oriol puede afectar a que no salga correctamente en Opendomo v2?
Me aparece el controlador pero no me deja asignarlo a ninguna habitación. Por último solo aparecen las entradas y no las salidas.

Saludos

**Comment by opalenzuela** [comment]
Este paquete es el heartbeat. Con él, el Arduino se da a conocer dentro de la red:

```
  ODC02:WTCHDG:devkt isalive
```

El siguiente paquete es el correspondiente a la información de estado:

```
  ODC02:WTCHDG di002 ON
```

Cuidado: el segundo grupo WTCHDG no es válido. Esto debería ser el UID, y solamente permite números codificados en hexadecimal.

**Comment by opalenzuela** [comment]
Os dejo un link a la documentación con el ejemplo:
http://opendomo.com/wiki/index.php/ODCBP

**Comment by Shegar81** [comment]
Entiendo que el UID y la MAC deben coincidir y por eso puede no funcionarme?

**Comment by opalenzuela** [comment]
En teoría están vinculados, pero el problema es más los caracteres y la longitud que odhal espera recibir, que igual filtra algo.

**Comment by cosmopaco** [comment]
Creo que con los últimos cambios, sera fácil construir la estructura de los mensajes para que sean  igual OD.

**Comment by Shegar81** [comment]
El UID en que fomato debe estar? En que forma debe transmitirse? Me refiero alfanumérico como la MAC representando como el hexadecimal?

Saludos

**Comment by Shegar81** [comment]
Hola, 

He instalado la ultima ersión de hoy en el Arduino. Después de analizar una trama de minuto y medio con el wireshark es como si los cambios de los puertos no los transmitiese por UDP. Por el puerto serie si que lo hace pero por UDP no sé por que no lo hace. 

He tenido que desmontar mi Raspberry esta semana estaré liado y fuera de casa así que hasta el finde que viene no puedo hacer las pruebas oportunas en este caso a través de la máquina virtual.

Deciros que con el cambio la representación por vía IP ( colocando la IP en el navegador) se vé muy fea.

Saludos

**Comment by Shegar81** [comment]
Hola Oriol,

Una duda en el Domino por que se separa si se tiene que transmitir de una forma o de otra? porque los eventos no se transmiten por todas las formas a la vez? 

Saludos

**Comment by cosmopaco** [comment]
Si tengo tiempo lo intento, No soy capaz de virtualizar Opendomo,
Mi router tiene la ip 192.168.xx.x.. y no me deja conectar con las 169.254.xxx, hace mucho tiempo lo conseguí pero no recuerdo como.
Salut

**Comment by Shegar81** [comment]
Buenas,

Haz la forma sencilla yo también uso esas IP, cámbialas en el programa y que lo que instales en el Arduino sea directamente la IP final. Es lo que yo suelo hacer. Nada más bajar el programa modifico el valor de la IP.
Para virtualizar Opendomo sigue las instrucciones de la web. Te descargas el OVA y enseguida se configura.

Saludos

**Comment by cosmopaco** [comment]
Este  Broadcast seria valido?
<code>
ODC01:123456789012 DI:ON
ODC01:123456789012 DI:ON
ODC01:123456789012 DI:ON
ODC01:123456789012 DO:OFF
ODC01:123456789012 DO:OFF
ODC01:123456789012 DO:OFF
ODC01:123456789012 DO:OFF
ODC01:123456789012 AI:+0253.0000
ODC01:123456789012 AI:+0024.0000
</code>

**Comment by opalenzuela** [comment]
No. Falta el nombre de puerto:
ODC01:0004A3123456 DI:**di000**:ON DI:**di001**:ON AI:**ai001**:+0023.5000

Nótese que pueden mandarse varios puertos en cada broadcast, y que únicamente hay que indicar el UID del Arduino una vez.

**Comment by cosmopaco** [comment]
Es verdad, no me había fijado!!!
Lo de enviar varios puertos, con la estructura que tiene ahora no es posible. 
Si  lo cambiara. Hay un limite del tamaño del mensaje? o de puertos?

**Comment by opalenzuela** [comment]
En principio no hay un límite de puertos. Lo recomendable (para simplificar) es que el envío se hiciera de todos los puertos, que tampoco hay tantos...

**Comment by cosmopaco** [comment]
Hola Oriol.
Lo he intentado hacer enviándolo en un solo paquete.
Error catastrófico, la librería Ethernet UDP , tiene un tamaño máximo del paquete.
UDP_TX_PACKET_MAX_SIZE 24;
Eso quiere decir que el error lo llevamos arrastrando desde hace tiempo. Ya que el paquete mas pequeño que enviamos ya supera ese valor.
<code>
0123456789012345678901234
ODC01:0004A3123456:odctl isalive
</code>
No se como hacerlo!!!!

**Comment by cosmopaco** [comment]
Al fin he conseguido hacer envíos correctos de broadcast.
Sigue sin comunicarse correctamente con Opendomo, 
Al final estoy utilizando ingeniería inversa, buff que faenon !!!!! 

Unas preguntas, que me ayudaran a entender como funciona todo esto.
ODControl 1 y ODControl 2 tienen el mismo broadcast?
Opendomo envía los comando por Telnet?
Como averigua ODC1 si los puertos son ocultos?

**Comment by opalenzuela** [comment]
Si, el broadcast estándar será el mismo. ODC1 se refiere a la versión del protocolo, no a la versión de ODControl.

**Comment by cosmopaco** [comment]
Me has liado mas aun, si cabe.
Que puedo utilizar ODC1 o ODC2?

Perdona si soy pesado, se esta convirtiendo en un reto personal!!!!
Saludos.

**Comment by opalenzuela** [comment]
Hehehe... disculpa. A día de hoy, OpenDomo OS sólamente reconoce ODC01, por lo tanto ignorará cualquier broadcast que indique ODC02.

**Comment by Shegar81** [comment]
Hola,

Perdón por mi ausencia de toda la semana. Estuve fuera por trabajo y sin conexión decente. Leí pero ya escribir y pruebas me era imposible.
Lo de ODC2 el que puede haberte liado era yo. Lo modifiqué pensando que era indicativo de que elemento transmitía, como si fuera el nombre. Fallo mío que interpreté erróneamente las indicaciones al estilo del UID.

Saludos

**Comment by cosmopaco** [comment]
Quedas perdonado. Jajajaja
Faltaria mas.

**Comment by Shegar81** [comment]
Gracias,
Oriol al final el UID y el MAC deben coincidir.

Saludos

**Comment by opalenzuela** [comment]
¿Debo entender que ya os funciona?

**Comment by cosmopaco** [comment]
No, no funciona!!!!!

**Comment by cosmopaco** [comment]
No hay manera de que los mensajes por UDP me funcionen correctamenete. 
El snifer me lee unos caracteres rarisimos y paquetes mas grandes de lo que son. Por el serial son correctos.

**Comment by cosmopaco** [comment]
Corrijo lo anteriormente dicho el programa sniffer que utilizaba, no funciona bien. El broadcast se envía correctamente. 
Opendomo OS no reconoce bien los puertos y no actualiza los cambios. 
No entiendo como trabaja Opendomo OS. 
Se comunica por telnet o solo coge los datos del broadcast?

**Comment by cosmopaco** [comment]
Os dejo una captura de broadcast. Opendomo OS sigue sin reconocer los puertos correctamente.
Curiosamente si los puertos de salida si inicialmente están en On los reconoce. Pero no actualiza.

Os dejo copia de los mensajes.
<code>
ODC01:12345678901A:devkt isalive
ODC01:12345678901A DI:di002:ON DI:di003:ON DI:di005:ON DO:do006:OFF DO:do007:OFF DO:do008:OFF DO:do009:OFF AI:ai000:+0253.0000 AI:ai001:+0024.0000
ODC01:12345678901A DI:di005:ON
</code>

**Comment by opalenzuela** [comment]
He abierto un Issue en la página de OpenDomo OS 2, ya que parece que el problema es global: https://github.com/opalenzuela/opendomo/issues/38

**Comment by Shegar81** [comment]
Hola,

Mucho lío que no me ha permitido hacer pruebas. Si es que sirve de algo mi humilde aportación decir que el UDP no me funciona. Me pasa lo de siempre. El secuenciado que se emite cada "x" segundos se emite pero los cambios de puerto esos ya no se reflejan. Sin modificar el programa más que poner la IP que a mi me interesaba se emiten los mensajes de 32 bytes de "XXXXX is alive" y cada cierto tiempo un mensaje de 31 bytes para cada uno de los puertos. 
A ver si esta semana puedo colaborar ni que sea un poco.

Saludos

**Comment by cosmopaco** [comment]
Verificado, funciona Ok
