### ISSUE TITLE
Colgado

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#13]
Hola,

Hoy tras varios días sin comprobar si comnicaban los equipos me ha dado por hacerlo. El Opendomo en Raspberry a pesar de un par de reset funciona correctamente. El Domino no sé porque no tenía comunicación vía web ni con Opendomo. Al realizarle un reset se ha normalizado. Con comunicación sin problemas podríamos decir que lo he tenido 10 días. Lo encontrais normal?

Como único dato de vez en cuando por cuestiones de conexión he tenido que ir reinicializando el hub donde estan conectados.

Saludos

**Comment by opalenzuela** [comment]
Es habitual que Arduino deje de responder pasadas horas (o días) desde su arranque. No tiene watchdog y el chip de red se calienta cosa mala. Va muy bien para pruebas puntuales, pero para dejarlo permanentemente en marcha, necesita algunos hacks. Por ejemplo, instalando disipadores en los chips y haciéndole un reset de forma periódica.
