### ISSUE TITLE
Calculo memoria eeprom

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#14]
Hola,

Tengo una duda con respecto a como está puesto el cálculo de los espacios de la memoria eeprom. Creo que hay un error que se arrastra desde el primer cálculo. En el primer cálculo se indica que para los puertos digitales habrá 130 bytes debido a que hay 10 puertos por los 13 slots. Entiendo que esos 10 puertos corresponden a los 14 que existen menos los tres de comunicaciones y uno más para la SD. Pero la forma de definir la reserva indica multiplicar el espacio reservado para cada slot por el número de puertos totales definidos en la variable. Así que sería 14_13 en vez de 10_13. Si estais de acuerdo con lo que digo el código debería modificarse de la siguiente manera : 
// =>  14x13 =182
# define EMVPORTSOFFSET (EMAPORTSOFFSET + (ANALOGPORTS \* EMPORTSLOT))  //=>182+(6X13)=260
# define EMLINKSOFFSET  (EMVPORTSOFFSET + (VIRTUALPORTS \* EMPORTSLOT))  //=>260+(30X13)=650
# define EMLINKSLOT  3
# define EMNETCFOFFSET  (EMLINKSOFFSET + (VIRTUALPORTS \* EMLINKSLOT))    //=>650+(30X3)=740

Aún así no se llegan a los 1024 que limita el UNO.

Saludos

**Comment by cosmopaco** [comment]
Tienes toda las razón!!!!!
Aunque no influye en nada al trabajo real del programa.

**Comment by cosmopaco** [comment]
Esta corregido con la ultima actualización.  
Shegar has testado los cambios?
Si es posible prueba a configurar varios tipos de enlaces. Recuerda hacer un sav despues de configurarlos.

Saludos.

**Comment by Shegar81** [comment]
Hola,

He comprobado el enlace directo y de momento me funciona. Al empezar a realizar conexiones y desconexiones estilo interruptor se me bloquea el Domino. En si el bloqueo es aleatorio. Hay veces que un par de horas y otras veces más adelante. Tengo una placa que le he implementado un watchdog y parece dura algo más. En sí bastante más aunque me he encontrado hoy con un bloqueo. Ahora como me indicó Oriol debo mirar tema de calentamientos.
En la parte de enlaces he visto que se ha modificado la forma de crearlos. Antes se hacía mediante dos instrucciones y ahora es solo una. 
La representaión web no se actualiza por si misma y ahora es un tanto aleatoria la aparición dentro del opendomo.

Seguiré investigando ya casi tengo entendido el funcionamiento del Domino a nivel de programación.

Saludos

César

**Comment by Shegar81** [comment]
Hola,
Después de revisar conexiones he observado que tenía un error en las mismas y lo del bloqueo rápido no es del todo feaciente lo que he puesto. Estoy de nuevo evaluándolo desde ayer por la noche. Tengo dos Arduinos en paralelo uno con Watchdog y otro sin. 
Esta noche continuaré en mi estudio del código para poder aportar algo más que solo las pruebas en las máquinas.

Saludos

César

**Comment by cosmopaco** [comment]
Buen trabajo Cesar.
Si tienes alguna duda sobre el código pregunta, responderé a lo que pueda.
Necesito un rato libre para montarme un probador en condiciones. " en casa del herrero cuchara de palo"  y si me sobra tiempo intentare que sea pueda ampliar para  MEGA.
Se que no es sitio para preguntar, lo hago de todas formas. De donde eres?

**Comment by opalenzuela** [comment]
Perfecto. Confírmanos si sigue produciéndose el error con las conexiones revisadas. 

Muy buen trabajo a los dos con el código! ¿Os parece que empecemos a planificar el cierre de la próxima versión?

**Comment by Shegar81** [comment]
Buenas,

Pues se sigue bloqueando. Aunque el de Watchdog parece que dura más y se bloquea antes el "normal". Aunque antes de un día se bloquea. En si lo tengo con un montaje sencillo. Cada uno he habilitado la entrada 7 como di y la 8 como do que ya viene de fábrica así. Los he enlazado y he puesto un puente entre la entrada 7 y el ground o los 5V según me va pareciendo. EN la salida 8 tengo conectado un LED una patilla y la otra al Ground, vamos al tierra. Pues con eso se bloquea, me atrevería a decir que el "normal" en cuestión de horas, y el otro en torno al día o algo menos. 
Ahora me queda la parte de disipadores, como detalle decir que la alimentación se realiza a través de USB, cable más adaptador de 220V a entrada USB. Estoy planeando también el hacerlo con entrada de 12 V a ver resultado. 
Al final el código hoy poco, en otro momento.
Por cierto soy de Barcelona. 

Saludos

César

**Comment by cosmopaco** [comment]
Las entradas no se pueden conectar a 12V directo, quemarías el micro, Tendias que poner optoacopladores, para test no es necesario.

Yo soy de Matarò.
Saludos.

**Comment by Shegar81** [comment]
Cuando digo lo de los 12V no sería para las entradas sino para la alimentación del Arduino. Ahora lo hago a través del propio USB. Sería alimentar a través del jack que tiene pero con 12 V que es lo máximo recomendable para que no se caliente. Por este jack la tensión puede ir de 7-16 para que funcione pero a partir de 12 se calienta de forma excesiva, o eso dice la página oficial.

**Comment by Shegar81** [comment]
A ver lo que dura, ahora la alimentación ya no es por el USB sino que es por alimentación de 12 V en el jack de 2,5mm.
