### ISSUE TITLE
PROGMEM

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#15]
Hola,

Si estamos utilizando esta función como es que no tenemos definido en el encabezado el: 
'#include avr/pgmspace.h'

Saludos

**Comment by cosmopaco** [comment]
No recuero bien a partir de que versión del IDE Arduino, ya no es necesario definirlo,

**Comment by opalenzuela** [comment]
¿Cerramos este issue entonces?

**Comment by cosmopaco** [comment]
Por mi si.

**Comment by Shegar81** [comment]
Por mi también

**Comment by opalenzuela** [comment]
Issue cerrado.
