### ISSUE TITLE
Perdida de una entrada de forma espontánea

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#18]
Hola,

En la línea de las investigaciones que estamos tratando en otros post he hecho avances. Lo he preferido poner en otro apartado por considerarlo si más no curioso.
Como sabeis tengo los dos arduinos MEGA en paralelo con solo una sutíl diferencia. Pues en los dos les ha pasado lo mismo y han dejado de funcionar correctamente. El fallo que he detectado es que la entrada que yo tenía configurada como interruptor me ha desaparecido en los dos casos. Al visualizarlo por la web he perdido en ambos casos la entrada 7. He pulsado el botón de reset y en el que tengo el perro guardián se ha recuperado inmediatamente. En el otro he tenido que mantener pulsado el botón de reset más tiempo.
Al tener control desde la web de los dos elementos podía encender y apagar el LED de la salida 8 sin problemas. 
Se me hace extraño que ha podido mandar esa desconfiguración de los equipos. Indicar que tengo una Raspberry con Opendomo 2 funcionando en la misma red. Por el momento no los detecta como puertos válidos ( ninguno de los dos ARduinos)

Saludos

César

**Comment by opalenzuela** [comment]
Interesante...

Cuando hablas del LED de la salida 8, ¿te refieres a un LED externo que tu has pinchado?

**Comment by Shegar81** [comment]
Exacto está pinchado el LED entre la salida 8 y un tierra. Una pata del LED está en la salida y la otra en el tierra no hay resistencias de por medio.  El "interruptor" de la entrada 8 no corresponde más que a un cabla que tiene un extremo pinchado en la entrada 7 y el otro lo voy conectando a tierra o a la salida de 5v del Arduino según me interesa.

Saludos

César

**Comment by opalenzuela** [comment]
Vaya... pues tiene pinta de ser algún leak de memoria, si sucede pasado un rato desde la activación.

Lo raro es que pase exactamente en el mismo puerto (el 7). Entiendo que el resto de puertos funcionan bien, ¿verdad? ¿Solamente afecta a los Mega?

**Comment by Shegar81** [comment]
En si deja de estar representado en la web. Es como si se desconfigurara. Es curioso que solo sea ese puerto a pesar que hay más configurados como entrada que se mantienen. Estaban funcionando ambos desde ayer por la noche a eso de las 22:00 y han dejado de funcionar a la vez. Hoy haré otra prueba. Uno lo dejo con la misma configuración y el otro cambiaré el puerto de entrada. Como característica diré que estaban conectados a tierra en ese momento.

No sé si solo es cosa del MEGA ya que solo tengo ese tipo de placa. 

El que esté en constante entrada no sé si le puede afectar. Quiero decir que tiene conectada la entrada siempre o a tierra o a 5 V no queda al aire en ningún momento.

**Comment by cosmopaco** [comment]
He entendido bien? Tienes un led sin resistencia a un port configurado como salida ? 
Si es así, es una temeridad para el  microcontrolar.
Lo de la entrada a una señal fija, es lo mas normal del mundo.

**Comment by Shegar81** [comment]
Hasta donde yo recuerdo se coemntaba que en Arduino era posible. Lo que pasa es que normalmente lo tengo en modo OFF, no está luciendo. Lo máximo que lo he hecho lucir es entorno a media hora.

**Comment by Shegar81** [comment]
ME he leído de nuevo y solo lo recomiendan para el pin 13 para el reesto hablan de poner resistencias. Ya le buscaré una para ponérsela......puede influir eso en los problemas? justo el puerto del LED no es el que da el problema.

**Comment by Shegar81** [comment]
Tengo un ligero avance. No de como solucionarlo pero si de mayor información. Se han repetido los problemas y eso que esta vez en uno de los Arduinos le cambié el puerto de entrada. En sí utilicé el 5 que por defecto es una entrada. Parece como si a eso de las 6 les pase eso. No puedo asegurar la hora exacta pero me fuí hace un par de horas y a mi vuelta es cuando he descubierto el fallo. La otra vez cuando publiqué fue por horas parecidas y puede que más cercano por eso digo lo de las 6. Ahora ya los LEDs estan hasta con resitencia. Es un tanto extraño parece como si fuera en alguna sincronización o algo parecido.

**Comment by cosmopaco** [comment]
Tiene toda la pinta que anule el puerto por ruidoso.
Lo curioso es que ocurra con un puerto configurado en un enlace tipo 'c'.
Intentare reproducirlo para averiguar el motivo.

**Comment by cosmopaco** [comment]
Ya he encontrado el error,es de programa. 
Hace un tiempo le comente a Oriol si podia anular esa funcion, ! No la veia clara, algo no me encajaba ! Gracias a tus pruebas y comentarios lo he visto.

En la funcion refreshPortStatus ports[i].changes solo se se verifica y resetea en los primeros 5 segundos, en  principio supongo que era su idea. El registro va contando en triggerrPortsChanges y se va acumulando, independientemente si se encuentra o no en esos 5 segundos.
RECTIFICO
Que ocurre si ha pasado una dia? Pues esta claro que seconds vuelve a ser menor de 5, y tenemos acumulado todos los cambios que se hayan producido en ese intervalo de 1 dia.

```
if (ports[i].changes >= MAXCHANGES) {                   // puerto ruidoso s
```

**Comment by Shegar81** [comment]
Hola,

El caso es que hoy tengo una pruebas que ahora me tienen totalmente descentrado. Os explico el experimento con sus variables y los puertos utilizados. Esta es la situación que quedan por la mañana a eso de las 11:00:
-Arduino MEGA con shield Ethernet sin Watchdog. Configurado el puerto 5 como entrada digital y con un puente entre esta entrada y el tierra. A la salida 8, configurada como salida digital, un LED con resistencia de 500 ohm y la otra patilla a tierra.Enlace entre entrada 5 y salida 8 de tipo directo. Desconectado de red. Solo con alimentación.
-Arduino MEGA con shield Ethernet con Watchdog. Configurado el puerto 7 como entrada digital y con un puente entre esta entrada y el tierra. Configurado el puerto 5 como entrada también puesto a tierra. Entrada 3 como entrada digital también y esta puesta a 5V con puente también como en los otros dos casos. Puerto 8 configurado como salida digital y puerto 9 también como salida digital. EN el puerto 9 se conecta un extremo de una resistencia de 500 ohm que está en serie con un LED que se conecta a tierra. La salida 8 estaba enlazada con la entrada 7 de forma directa. La salida 9 estaba enlazada con la entrada 3 de forma inversa. Esta queda conectada a red Ethernet. También se coencta alimentación externa por jack de 2,5 mm.

A mi llegada a casa a las 19:30 me encuentro con la siguiente situación:
-Arduino desconectado de red bloqueado que no le funciona la entrada 5. Tras un reset como de costumbre empieza a funcionar correctamente. 
-Arduino conectado a red funcionando correctamente y sin anomalías.

Ahora no sé donde puede estar el problema. A ver como continuamos. Se os ocurre algo?

Entre medio no ha habido ningún cambio de estado ya que nadie los ha manipulado.

Saludos

César

**Comment by cosmopaco** [comment]
Prueba estas modificaciones,  cuando puedas.
https://www.dropbox.com/s/1gxzhjrupno0mhe/dominosaveLink.ino
No tengo el probador todavía, mañana lo acabo y pruebo yo también.

**Comment by Shegar81** [comment]
Lo he cargado en el Arduino sin watchdog y lo tendré sin conectar a la red ethernet de casa. En si solo le pondré alimentación y le configuro los enlaces entre entradas y salidas como la anterior vez
Mañana por la tarde o mejor dicho por la noche cuando llegue a casa indico resultados. El que tiene watchdog sigue conectado a la red y funcionando perfectamente. Lo dejaré así hasta mañana y a ver que pasa.
No sé que has quitado pero ha dejado más memoria libre, normalmente marcaba entorno a los 6040 libres y ahora está en 6250.

**Comment by Shegar81** [comment]
A ver como responde la nueva versión. Al levantarme y probar antes de irme a trabajar el que estaba en red está bloqueado y ha necesitado un reset. Creo es algo de programa. Lo curioso es que han desaparecido las tres variables que tenía conectadas. Me explico algo mejor, las tres entradas que tenía configuradas como entradas digitales y que tenían algún puente ya fuera a tierra o a 5 voltios estaban deshabilitadas. Después de reset con botón todo se normaliza.
A ver como funciona cuando llegue la nueva versión que me pasaste.

**Comment by Shegar81** [comment]
De momento con el nuevo código no se ha bloqueado. Si mañana por la mañana encuentro e del Watchdog bloquedado le instalaré el programa modificado y los intercambiaré en lo que a conexión a red se refiere. 
Dejemoslo un par o tres de días a ver que pasa.
Que modificación le hiciste al programa?

**Comment by cosmopaco** [comment]
Modifique la función de alunar un puerto ruidoso.
Introduciendola dentro de la función triggerPortChange.

```
     static unsigned int oldseconds;    // Antiguo valor de seconds.
    if (ISINPUT (port)){

      ports[port].changes++;

      if (oldseconds != seconds){            //Reseteamos cada segundo.
        ports[port].changes=0;
        oldseconds=seconds;          
      }
      else if (ports[i].changes >= MAXCHANGES){
        ports[i].type = 'N';            // Desactivado
      }

    }
```

Hay un error en el calculo de seconds  y days, la variable seconds esta declarada como tipo unsigned int. y tiene que contar los 86400 segundos de un día, imposible. 
No se en que momento te bajaste el skecth también declare mal oldseconds tipo int. No se exactamente como se compilara pero no tiene que ser problema.
Esto no influye en el problema que estamos tratando.

**Comment by opalenzuela** [comment]
Cosmopaco, si quieres hacer el pull request será más fácil para todos mantener el código.

En cuanto a los puertos ruidosos, si queréis podemos desactivar esta opción y dejar en manos del usuario verificar que todas las conexiones están correctas. Es una feature que viene de las primeras versiones, donde era necesario hacerlo así, pero más tarde implementamos los pulldowns y se reduce enormemente el impacto de una mala conexión,

¿Qué os parece?

**Comment by cosmopaco** [comment]
Hola Oriol.
Mi nombre es Francisco Cosmo., podéis llamarme Paco. 

Soy bastante desordenado, aparte de no acabar de entender como funciona Github. 
No se si te han llegado mensajes de prueba, que no se ni donde los envíos. Intentare hacerlo mas ordenado y leer algún manual para acabar de entenderlo.

Modificare el tema de puerto ruidosos. 

Me has desconcertado con el tema de los pulldowns. Yo trabajo con microcontroladores Microchip, hasta hace podo solo programaba en ensamblador, con lo cual te tienes que revisar todos los registros del puerto para empezar a trabajar. Nunca había visto que un puerto se pudiera configurar en modo pull-down he mirado el datasheet de atmega y tampoco tienen esta opción. Supongo que te refieres a pullup para hacer pulldown tienes que ser con resistencias externas.

Toda esta parrafada también sirve para explicar que lo "habitual", es que las entradas se suelen utilizar con la polarización interna del microcontrolador pullup y elementos externos hundan a GND esta entrada. De esta forma no influye el valor de la alimentación del microcontrolador 5V, 3V, bateria etc.

Esto va por Cesar, no es necesario ni aconsejable poner los 5V en las entradas, es lo mismo que dejarlas al aire. Ademas si no me equivoco existe algún modelo de Arduino que trabaja a 3V si le ponemos los 5V a la entrada lo achicharramos.

Saludos.

**Comment by Shegar81** [comment]
Hola,

Le pongo los 5V que salen del propio Arduino, no proceden de ninguna fuente externa. Son de la pata que pone 5V. He visto que los puertos se quedan configurados en pullup pero era para forzar aún más ese valor alto. 
Volviendo más al tema de las entradas os comento que el que no tiene el código último se ha vuelto a bloquear. Es curioso pero solo se desconfiguran aquellas entradas que tienen un enlace, las otras a pesar de tener en este caso un puente respecto a tierra no se an desconectado. Refresco un poco. El Mega tenía configurados los puertos 3, 5,7,8 y 9. Los pertos 3,5y 7 estaban configurados como entradas digitales. Los puertos 8 y 9 como salidas digitales. Además se habían enlazado el puerto 7 con el 8 y el 3 con el 9. Pues los puertos que se han desconfigurado han sido solo el 3 y el 7. Al conectarte a la IP del Arduino desaparecen. Tras un botonazo en el reset todo vuelve a la vida. El Arduino estaba conectado a red.
El que tengo desconectado de red y que tiene el último código pues sigue funcionando correctamente. Ahora lo que haré es modificar el código para insertarle el Watchdog, por eso no lo subo aquí, y probar este Arduino en red y a ver cuanto dura. Tendrá la misma configuracón antes descrita.
Oriol si la modificación de Paco ha sido el desconectar lo de los puertos ruidosos parece funciona correctamente. Yo entiendo que como mis pruebas estan yendo de momento en la parte de entradas y salidas digitales no le afectará. Tal vez cuando empecemos con los analógicos nos llevemos más sorpresas, pero vayamos poco a poco si os parece. 

A mi modo de ver está siendo unos ensayos de prueba error basante dinámicos. Es cierto Oriol en lo que dices que tal vez no estamos sacándole el provecho adecuado de Github, vayamos aprendiendo para sacárselo. Valdría la pena abrir un mensaje exclusivo de funcionamiento de Github?

Saludos y perdón por el ladrillo.

César

P.D: Oriol si se te ocurre alguna prueba que crees interesante hacer no dudes en decirla al igual que Paco.

**Comment by cosmopaco** [comment]
El código de dropbox no se ha desconfigurado?
He entendido bien?

**Comment by Shegar81** [comment]
Exacto

**Comment by cosmopaco** [comment]
Si realmente el problema es la rutina de puerto ruidoso. quede de echo esta mal.
Es logicoo que se desconfiguren las entradas con enlace, ya que son las que tu has manipulado mas veces. 
Con lo cual el contador ports[].Changes tiene el numeros de veces que ha cambiado y como ya dije la desactivara cuando seconds se desborde volviendo a cero.

**Comment by opalenzuela** [comment]
Ante nada mis disculpas. Es cierto lo de los pulldowns. Me confundí con ODControl. Evidentemente me refería a pullups. (hace demasiado tiempo que no me peleo con el Arduino!!)

En cualquier caso, mi punto era que la funcionalidad de detección de los puertos ruidosos no es necesaria y puede deshabilitarse, en especial si causa problemas que pueden ser de diagnóstico complicado.

¿Qué os parece? ¿Lo quitamos?

**Comment by cosmopaco** [comment]
No son necesarias las disculpas, se aprende de los errores. Solo era para tener claro el funcionamiento.
La funcion se elimina, cuando tenga un rato actualizo.

**Comment by Shegar81** [comment]
Hola,

Después de implementar el último programa de domino en mi Arduino y dejarla funcionar más de un día me ha vuelto a pasar el mismo problema.......Así que lo reabro. Los puertos desaparecidos estaban puestos a tierra mediante un puente a la patilla GND del Arduino.

Lo siento.

César

**Comment by cosmopaco** [comment]
El hombre de los puertos que desaparecen.  Jajaja.
Cuando dices el ultimo programa a cual te refieres al de github o al beta?
Yo tengo funcionando el de github durante mas de una semana sin problema.

**Comment by Shegar81** [comment]
El de Github. Lo tengo en red y con alimentación externa respecto a la de USB, me refiero por el jack. Si te conectas por Http lo ves todo correctamente?

**Comment by cosmopaco** [comment]
Si.
No  he detectado nada. Activare algunas de las entradas y salidas para probar..

**Comment by cosmopaco** [comment]
No he sido capaz de reproducir este error. En cambió he detectado #37

**Comment by cosmopaco** [comment]
resolved #18
