### ISSUE TITLE
"lsc" syntax

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/dominoOSE#2]
Adapt lsc syntax to the ODControl 1.6 protocol

**Comment by Shegar81** [comment]
LSC? Que es?

**Comment by opalenzuela** [comment]
"lsc" es un comando que reemplaza al "lst". Contiene toda la información necesaria para representar cada uno de los puertos y no es ambiguo como "lst": http://www.opendomo.com/wiki/lsc

**Comment by Shegar81** [comment]
Entiendo que querrías que se implementara en el DOMINO?

**Comment by opalenzuela** [comment]
Sí, pero de cara a la versión 1.1.6. Aún queda tiempo para eso.

**Comment by opalenzuela** [comment]
He modificado este issue para intentar implementarlo en la próxima versión, y explicaré la razón.

En cuanto Domino tenga el comando "lsc" implementado, ya podremos usar la herramienta de configuración de ODControl1.6 también para configurar nuestro Arduino. Creo que es un paso de gigante y que, por tanto, vale la pena priorizarlo.

En cuanto empecemos a usar el configurador, saldrán a la luz otras modificaciones necesarias, así que parece un buen punto de partida.

**Comment by Shegar81** [comment]
Me lo parece a mi o actualmente de la forma que hace el comando lst ya sería sutituible el formato y poco más.

Saludos

**Comment by opalenzuela** [comment]
Correcto. Según el manual, la sintaxis de "lst" es la siguiente:

 lst
 DO:do000:OFF
 DO:do001:OFF
 DO:do002:OFF
 DI:di000:OFF
 DI:di001:OFF
 DI:di002:OFF
 DI:di003:OFF
 AI:ai000:+0051.0000
 AI:ai001:+0034.0000

Mientras que la de "lsc" sería:
  do000:DOM0:ON
  do001:DOM0:OFF
  do002:DOMl:OFF
  do003:DOMl:OFF
  di000:DIMl:OFF
  di001:DIMl:ON
  di002:DIMl:OFF
  di003:DIMl:OFF
  ai000:AIM_:-0001.2500:00000|00001:_:

**Comment by cosmopaco** [comment]
No acabo de entender los puertos analogicos.
En el lst aparece su valor con dos enteros con signo separados por un punto.
En Domino se utiliza un variable de 1 Byte para los puertos analogicos!!!!

**Comment by opalenzuela** [comment]
El valor del puerto analógico de entrada se representa con el formato:
    +0001.2500 

Que vendría a ser +1.25

En caso de ser negativo, pondríamos un -, y en el caso de Arduino, los decimales siempre estarían a cero (solamente estaría leyendo valores entre 0 y 255). En ODControl soportamos decimales y negativos, pero en Arduino no tenemos potencia de cálculo ni memoria suficiente para   tanto detalle....

**Comment by Shegar81** [comment]
Así que según lo que comentas se debería representar conforme los valores van de +0.00 a +255.00, es correcto?

Saludos

César

**Comment by opalenzuela** [comment]
Correcto. Pero con 4 decimales, y añadiendo los ceros en la izquierda para mantener el ancho fijo.

```
+0000.0000 a +0255.0000
```

**Comment by Shegar81** [comment]
Esta representación Oriol debería ir cuando lo hace en HTML? o en funcionamiento interno también?

**Comment by opalenzuela** [comment]
Esta representación es solamente cuando se recibe el comando "lsc". Internamente lo podemos guardar en enteros (byte)

**Comment by cosmopaco** [comment]
Un par de preguntas.

Cesar: Estas implementando el comando lsc?

Oriol: Según el manual ODControl las definiciones de las características del puerto son:

Primera letra:
D: Digital
A: Analógico
Segunda letra:
O: Salida
I: Entrada
V: Virtual
X: Deshabilitado
Tercera letra:
M: Visible en la pestaña Home
C: Visible en la pestaña Config
H: Oculto

Mas abajo hay un ejemplo que aparece.
vt036:VXH_:
vt037:VXH_:
vt038:VXH_:
vt039:VXH_:
vt040:VXH_:
vt041:VXH_:

Siendo la primera letra, puerto virtual?????

**Comment by opalenzuela** [comment]
VXH_ = Puerto virtual, deshabilitado, mostrado en el "home" y sin etiquetar... no tiene mucho sentido, la verdad.

Los puertos cuyo nombre empieza por "vt" son efectivamente virtuales.

**Comment by cosmopaco** [comment]
No me has entendido.
En la definición del orden de las letras. la primera letra solo especifica D o A, y pones en la segunda si es virtual. Supongo que es un error?

**Comment by opalenzuela** [comment]
Ah, entiendo. Sí, efectivamente es un error. A, D y V pueden estar en la primera letra.

**Comment by cosmopaco** [comment]
Thanks.

**Comment by Shegar81** [comment]
Hola,

Perdón por estar desaparecido estos días, pero este fin de semana he estado trabajando los dos días, cuestión laboral no de este proyecto. 
Paco no he avanzado estuve recapitulando para ver como hacerlo. He de decir que tengo nociones de programación pero toqué un poco en la carrera de micros pero hace ya unos años. Voy avanzando a pasos agigantados para poderme poner a tu nivel en este proyecto. 
Intentaré en esta semana, más bien para finales mirarme lo que has ido implementando. Ví el video y solo tengo que felicitarte por tu probador, me encantó lo del pulsador que sube y baja intensidad estando pulsado, está implementado en el que está aquí subido?
Que tal si nos marcamos como meta ahora el hacer que este LSC funcione  después buscamos nuevos retos. En sí veo que te lo curras muchísimo y casi te los marcamos a tí......
Tengo la sensación que se está avanzando mucho en este proyecto.

Saludos

**Comment by cosmopaco** [comment]
Hola.

Me siento elogiado y lo agradezco.

El probador es un poco "de estar por casa" pero hace su trabajo.

Lo de subir y bajar la intensidad, se trata del enlace  ' l ' , Esta implementado desde hace un tiempo en la ultima versión he ajustado los tiempos,y un pequeño error. Ahora leyendo el manual
no es exactamente igual al de ODControl.
Este tipo de enlaces solo se puede utilizar con una salida configurada como ao (analog out) que en realidad es PWM.

Sería conveniente actualizar el manual de Domino, intentare hacer un boceto  para actualizar los comandos actuales. 

Enlazar puertos (lnk)
Crea un enlace entre un puerto de entrada (primer argumento) y un puerto de salida (segundo argumento), indicando en tercer lugar el tipo de enlace. El tipo puede ser uno de los siguientes:

d (directo) Si el puerto de entrada se pone a "on", el puerto de salida se pondrá también a "on". Entrada y salida siempre tendrán el mismo valor.

i (inverso) Si el puerto de entrada se pone a "on" el de salida se pone a "off". Entrada y salida siempre tendrán valores opuestos.

p (pulso) Si se recibe un pulso en la entrada (off -> on -> off) el puerto de salida cambiará de valor. Si está en "on" pasará "off" y viceversa.

l (Pulsación larga) Regula una variable analógica según el tiempo se mantenga pulsado el pulsador.
'l': Incrementa el valor de un puerto analógico entre 0 y 100, o lo disminuye, en 5 segundos. El funcionamiento es el siguiente:

Una pulsación larga mantenida hace augmentar el valor de la variable a razón de un 20% por segundo.

Una pulsación corta seguida de una larga hace disminuir el valor del puerto analógica a razón de un 20% cada segundo.

Una pulsación corta hace subir al 100% el valor de puerto analógico si este era 0 o lo devuelve a 0 si su valor se encontraba superior a 0.

c (conmutado o cambio) Si se realiza un cambio en el puerto de entrada (on -> off, off -> on) el puerto de salida cambiará de valor independientemente de su estado actual (on, off). Si está en "on" pasará "off" y viceversa. Entrada y salida no tienen porqué tener el mismo valor

r (retorno) Si el puerto de entrada cambia de valor, el puerto de salida se pone a "on" y después regresa a su estado "off", generando un pulso de unos 500ms.

t (retorno en subida) Si el puerto de entrada se pone a "on", el puerto de salida se pone a "on" y después a "off", generando un pulso, igual que el enlace de tipo r.

s (self, reflexivo) Si el puerto de entrada se pone a "off", el puerto de salida se pone a "on" y después
a "off" (pulso). Si el puerto de entrada se pone a "on", el puerto de salida se pone a "off". Se utiliza para crear un enlace con un mismo puerto origen y destino, con el objetivo de que siempre que cambie vuelva a "off" (ej: lnk do000 do000 s).

n (contador) Incrementará el destino en el flanco de bajada.

N (contador) Incrementará el destino en el flanco de subida.

o (ON) Cuando el origen cambia de valor el destino se pone a ON.

f (OFF) Cuando el origen cambia de valor el destino se pone a OFF.

**Comment by opalenzuela** [comment]
Chicos, aflojad un poco!! Siento no poder dedicar más tiempo para ayudaros en el desarrollo, pero tengo otros frentes abiertos a los que no puedo quitar tiempo de dedicación... 

Veo que prácticamente todas las funcionalidades están ya operativas, así que en cuanto tengamos el comando "lsc" bien implementado (y por tanto, alcancemos la compatibilidad plena con ODControl) podremos empezar a compartir herramientas de configuración entre ambos dispositivos. En mi opinión, ése será el próximo paso de gigante en el proyecto Domino.

Gran trabajo!

**Comment by cosmopaco** [comment]
Tranquilo Oriol, yo voy haciendo cuando me apetece.
Soy de Matarò ya se sabe un CapGros...JAJAJAJA

**Comment by cosmopaco** [comment]
En OdControl las repuesta a "lst" y "lsc" tiene algún tipo de mensaje de cabecera?
En en manual no se indica. En Domino el comando "lst" tiene cabecera.
"lsc" tiene subfunciones es necesario implementar alguna de ellas,  para que sea compatible con ODContorl?

**Comment by opalenzuela** [comment]
No, no necesita cabecera. Simplemente el nombre del puerto seguido de dos puntos, el tipo indicado con 4 letras y el valor. El resto de campos no los usaremos por ahora.

**Comment by cosmopaco** [comment]
Tengo adaptado el código con las características que hemos ido comentando.
He tenido que modificar varias funciones, de momento estoy probando que no hayan errores.
No se si subirlo a github o poner un enlace de descarga y que alguien más lo pruebe?

**Comment by opalenzuela** [comment]
Súbelo al github, y lo etiquetaré como versión cuando esté estable.

**Comment by cosmopaco** [comment]
Subido.
He intentado comentarlo lo mejor posible. 
Seria conveniente que lo comentarais con términos mas técnicos. Yo soy autodidacta y no conozco los palabros de programación.

**Comment by cosmopaco** [comment]
Donde esta la herraminenta de configuracion de ODcontrol?
La interface web carga javascripts, que trabaja con Ajax, creo que no es muy compatible con Domino!!!

**Comment by cosmopaco** [comment]
Perdon

**Comment by opalenzuela** [comment]
En ODControl sí funciona, y no debería ser muy complicado hacerla funcionar si en Domino se pueden pasar los comandos por HTTP (como por lo menos antes se podía). No tenemos ninguna versión de Configurator para Domino OSE, por lo que de momento fallarán muchas cosas, pero para empezar podeis probar de incluir este javascript:

http://cloud.opendomo.com/odctp/global1.6.3.js

**Comment by cosmopaco** [comment]
Perdona Oriol, no se ni por donde empezar. 

Donde tenemos que incluir el javascript?
Creo que tenemos que cambiar el html que genera Domino para que funcione, como ha de ser el body?

Si alguien sabe que se encargue, yo se muy poco o nada.

**Comment by opalenzuela** [comment]
He subido los cambios pero no tengo el Arduino para probarlo. No os asustéis si se rompe la visualización: esto va a tomar algo de tiempo, pero valdrá la pena!

**Comment by cosmopaco** [comment]
Lo pruebo cuando pueda, Gracias

**Comment by cosmopaco** [comment]
Efectivamente se ha roto la visualizacion. La pagina home solo texto, sn imagenes ni iconos. 
Intento averiguar como funciona.
Saludos.

**Comment by opalenzuela** [comment]
Puedes pasarme el HTML?

El 08/03/2014, a les 11:26, cosmopaco notifications@github.com va escriure:

**Comment by cosmopaco** [comment]
Si, aquí lo tienes.
Para que se pueda leer e sustituido "< " por "/".

/!-- saved from url=(0023)http://169.254.0.10/lst -->
/html>/head>/meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">/title>Domino//title>/meta name="viewport" content="width=320">/link type="text/css" href="./Domino_files/ar.css">/script src="./Domino_files/global1.6.3.js">//script>//head>/body>/divid=main>/div id="h">//div>/ul id="frm" class="ls&lt;li">/b>di002//b>/a class="ON">//a>
/li class="DI">/b>di003//b>/a class="ON">//a>//li>
/li class="DI">/b>di004//b>/a class="ON">//a>//li>
/li class="DI">/b>di005//b>/a class="ON">//a>//li>
/li class="DO">/b>do006//b>/a class="OFF" href="http://169.254.0.10/set+do006+on">off//a>//li>
/li class="DO">/b>do007//b>/a class="OFF" href="http://169.254.0.10/set+do007+on">off//a>//li>
/li class="DO">/b>do008//b>/a class="OFF" href="http://169.254.0.10/set+do008+on">off//a>//li>
/li class="AI">/b>do009//b>/a>00000//a>//li>
/li class="AI">/b>ai000//b>/a>00253//a>//li>
/li class="AI">/b>ai001//b>/a>00024//a>//li>
//ul>/a id="f" href="http://opendomo.com/">v
1.1.4 //a>
//divid=main>//body>//html>

**Comment by cosmopaco** [comment]
Una cosa curiosa que no se de donde sale.
En la interface web  al hacer clic sobre una salida, el modo serial de Domino me muestra lo siguiente.

HTTP CMD:set+do006+off 
N:devkt.do006 value OFF
ODC01:123456789012 AO:ÿÿÿÿÿ:000
N:board cmdok
http_in 
set+do006+off HTTP CMD:lst 
http_in 
lst HTTP CMD:favicon.ico 
E:board error 1
http_in 
favicon.ico ODC01:123456789012:devkt isalive

De donde sale una entrada http llamada favicon.ico ?

**Comment by opalenzuela** [comment]
Esto es una llamada que hace el navegador para conseguir el icono de la página.

**Comment by cosmopaco** [comment]
Me he documentado un poco y he intentado evitarlo, es casi imposible.
Los navegadores interrogan al servidor con múltiples y diferentes envíos  "GET/XXXXx".

He leído una solución un poco simple pero creo que efectiva, hay un contra, no esta implementado en ODControl ni en el javaScript. La solución es utilizar en todos los envíos AJAX un carácter inicial siendo '?', la lectura del cliente solo se guarda y responde a partir de este carácter.

Es solo una idea, se que implica mucho trabajo, pero aquí la dejo.

**Comment by opalenzuela** [comment]
No vale la pena invertir tiempo en esto, simplemente preparar al firm para que ignore este tipo de peticiones. 

Para arreglar el tema visual, estoy intentando recuperar el Arduino Ethernet que usé en su momento, pero al parecer está dañado. Sería interesante deshacer los últimos cambios que hice para que, por lo menos, podáis seguir usando la interfaz estable...

**Comment by cosmopaco** [comment]
Haber si me explico. Como ya he comentado se muy poco de CSS y JavaScript.
El primer problema es que esta mal escrita la referencia al css.
Deberia quedar así.

prog_char str_http_header_1[] PROGMEM = "<html>\n<head><title>Domino</title><meta name=";
prog_char str_http_header_2[] PROGMEM =  "viewport content='width=320'/><link rel=styles";
prog_char str_http_header_3[] PROGMEM =  "heet type='text/css' href='http://cloud.opendo";
prog_char str_http_header_4[] PROGMEM =  "mo.com/odctp/ar.css'/><script src='http://cloud.";
prog_char str_http_header_5[] PROGMEM =  "opendomo.com/odctp/global1.6.3.js'></script></hea";
prog_char str_http_header_6[] PROGMEM =  "d><body><div id=header></div><ul id=frm class=lst>";

NOTA: NO SE COMO HACER QUE SEA VISIBLE.

Aun haciendo esto hay un problema con el Javascript. No se crean los iconos.
He visto que addEventListener en el JS anterior hace referencia a header en el nuevo JS no lo hace,

<code>
addEventListener("load",function(){
    var p = document.getElementById("log");
    if (p) {
        var fileref=document.createElement("link");
        fileref.setAttribute("rel", "stylesheet");
        fileref.setAttribute("type", "text/css");
        fileref.setAttribute("href", "http://cloud.opendomo.com/odctp/odc.css");
        document.getElementsByTagName("head")[0].appendChild(fileref);
        loadjscssfile("http://cloud.opendomo.com/odctp/index.php?id="+document.title, "js");
        document.title = "Log window";
        //loadMenu();
    }
</code>
Creo que falta alguna clase o identificador ?
No entiendo como empieza el JS a generar la pagina, es un login?

**Comment by opalenzuela** [comment]
Por ahora no os preocupéis de esta parte. He deshecho los cambios hasta que pueda conseguir un Arduino Ethernet para hacer las pruebas como es debido, ya que he visto que los cambios en el HTML van a tener que ser masivos para soportar el configurador de ODControl. 

Mientras tanto, el objetivo de este Issue era generar el formato adecuado para el comando "lsc". ¿Podríais hacer un copy-paste del formato que sale ahora? Si es correcto, cerramos Issue.

**Comment by cosmopaco** [comment]
ÿÿÿÿÿ:XXÿ_:
ÿÿÿÿÿ:XXÿ_:
di002:DIM_:ON
di003:DIM_:ON
xxx01:XXH_:
di005:DIM_:ON
do006:DOM_:OFF
do007:DOM_:OFF
do008:DOM_:OFF
do009:DOM_:OFF
xxx02:XXH_:
xxx03:XXH_:
xxx04:XXH_:
xxx05:XXH_:
ai000:AIM_:+0253.0000
ai001:AIM_:+0024.0000
ai002:XXC_:
ai003:XXC_:
ai004:XXC_:
ai005:XXC_:
vt000:VXC_:
vt001:VXC_:
vt002:VXC_:
vt003:VXC_:
ODC01:123456789012:devkt isalive

Hay lo tienes.

**Comment by cosmopaco** [comment]
Hay un problema que no había detectado antes.
La respuesta de los comandos lsc y lst en modo serial "aparentemente" esta bien, pero al utilizar Telnet no es correcta.
Para crear la cadena de salida, se utiliza la función get_state. Esta función también se utiliza para generar  el Broadcast, y en el caso de los puertos analógicos, no funciona correctamente.

He estado experimentando, sin conseguir resolverlo. Me ha surgido una duda.

En las respuestas con comunicación telnet han de acabar con retorno carro '\r' salto de linea '\n', o solo con salto de linea?
Otra cosa.
En el caso de webserver que terminación debe tener?

Saludos.

**Comment by cosmopaco** [comment]
Hola.
Estoy atascado con los finales  de linea.
Alguien sabe como tienen que ser?

**Comment by opalenzuela** [comment]
Disculpa, se me pasó el mail.
Tienen que ser "\n", formato Linux, también para el webserver.

**Comment by cosmopaco** [comment]
Hola,
Publicada unas correcciones. 
La respuesta al comando lsc tenia un error que he corregido, el broadcast esta mejorado.
De todas forma hay algún error que hace que Opendomo OS no lea bien los puertos.

**Comment by cosmopaco** [comment]
Estoy observando que los puertos analogicos envian mas datos.
Si no son necersarios cerramos?

**Comment by cosmopaco** [comment]
Cierro.
El comando lsc responde correctamente.
Falta crear las diferentes opciones de lsc y lst.
