### ISSUE TITLE
Comando "lnk" guarda puertos que no existen.

### ISSUE THREAD

**Issue by cosmopaco** [opalenzuela/dominoOSE#21]
Haciendo pruebas de configuracion me he encontrado este error.
Envias el siguiente texto, donde di001 no extise.

lnk di001 do008

Devuelve Error 101 y despues cmd Ok.

Vemos los enlaces con lln  en lugar di001 aparece un nombre con caracteres extraños.

El problema esta en la  funcion getPortId, que puede dar otros errores.
La devuelve un valor sobre una varable declarada como byte. (8 bits sin signo en Arduino). Si el port recibido no existe devuelve -1. Que devuelve exactamente?

Por otro lado al procesar las instrucciones recibidas llamamos primero a getPortId y el resultado lo enviamos como byte a la funcion lnk. Que comprueba si el puerto es valido con port ==-1. En realidad no reconoce que no es valido y buscara en una direccion no existente.

**Comment by opalenzuela** [comment]
Vaya... pues si lo que dices es cierto, la función hará overflow y devolverá un 255, que es un elemento del array que no existe, por tanto: basura. Hay que cambiar este tipo de dato a un entero (8 bits) con signo.

**Comment by cosmopaco** [comment]
Es bastante complicado, se tiene que  hacer con mucho cuidado.
He estado repasando el código y se utiliza dentro de otras funciones o se les pasa el resultado por parámetro.
Las variables de entradas de las funciones se han declarado como tipo char, usigned char, byte.... 
un lío.

Que tipo de datos utilizamos, char  máximo 127 o int  mas ram utilizada y mayor tamaño de programa?

**Comment by opalenzuela** [comment]
Para numeración de puertos, siempre tendría que ser signed char, ya que nunca vamos a tener más de 127 puertos en Arduino. Y nos interesa tener negativos para detectar el caso de "puerto no encontrado"

**Comment by cosmopaco** [comment]
Tengo el código modificado.
PERO NO ME ENTERO DE COMO FUNCIONA GITHUB. Grrrrrrrrr.
Cuando me tranquilice un poco, vuelvo a mirar la manero de subirlo.

**Comment by opalenzuela** [comment]
Se me ha enviado sólo. Si tienes el programa gráfico  solamente tienes que hacer commit y sync.

**Comment by cosmopaco** [comment]
Que se ha enviado solo?
Definitivamente Github Windows y Win 7 64bits no son amigos.
Lo he toqueteado tanto, que no me deja ni clonar el reposotorio.

**Comment by opalenzuela** [comment]
Vaya... Si quieres, puedes pasármelo y lo subo yo mismo.

**Comment by cosmopaco** [comment]
Conseguido.
resolve #21
