### ISSUE TITLE
Presentación, saludos y kick-off

### ISSUE THREAD

**Issue by DeGaido** [opalenzuela/dominoOSE#25]
Hola, soy Guillem, nuevo en domino y OpenDomo, 

estoy empezando con el proyecto de domotización de mi viviendo y en encontrado en Opendomo la solución que mas me gusta. 

voy a empezar jugando con dominio y OD para así aprender un poco más sobre el systema y a su vez intentar aportar mi granito de arena.

estoy a vuestra disposición! :-)

Ahora mismo estoy trabajando OD 1.0.0 y domino 1.1.4. Me parece que el manual de refencia de domino esta un poco obsoleto http://www.opendomo.com/wiki/index.php?title=Manual_de_referencia_de_Domino. Es posible?

En concreto ayer estube utilizando el comando eth para establecer los parametros de red y solo encontré operativo la varainte eth ip para establecer la IP. Revisando el código he encontrado que las variantes "eth gw" y "eth nm" estan desabilitadas y la variante "eth mc" no tiene relevancia ya que la mac se define en el código.

Saludos, 
G.

**Comment by opalenzuela** [comment]
Bienvenido!

Cierto, el manual de referencia ha quedado algo obsoleto, pero de hecho hemos pensado que lo más lógico sería trasladarlo poco a poco en esta propia wiki:
https://github.com/opalenzuela/dominoOSE/wiki 

De este modo, todos vosotros tendréis la posibilidad de participar en su desarrollo y mejora constante.

**Comment by cosmopaco** [comment]
Hola, soy Paco. 
Tienes toda la razón el manual esta obsoleto. De momento hemos ido cambiando código y no se ha documentado demasiado. Los cambios son para acercarlo a ODControl, por consiguiente se pueden utilizar fragmentos del manual de ODControl.

Como hasta ahora yo he hecho la mayoría de cambios, intentare hacer un borrador. No se me da nada bien escribir, si algún voluntario lo ordena!!!!!

**Comment by DeGaido** [comment]
Hola Paco, yo mismo te ayudaré con el manual!
G.

**Comment by Shegar81** [comment]
Hola Paco,
Soy César.
La parte de documentación algo te puedo ayudar más de lo que he ido haciendo hasta ahora. 

Saludos

**Comment by DeGaido** [comment]
Hola,

La verdad, no me aclaro mucho aun con el github. He intentado crear  contenido en la wiki pero tengo algunas dudas referentes al funcionamiento de github:
- opalenzuela/dominoOSE es el repositorio original. Yo me he creado un fork DeGaido/dominoOSE. Cómo se transfieren mis modificaciones al wiki del repositorio original?

En cuanto a la documentación a crear, @cosmopaco propusiste utilizar fragmentos del manual de ODControl, yo podria empezar a copiarlo (con permiso de @opalenzuela), donde puedo encontrarlo.

Saludos, 
G.

**Comment by DeGaido** [comment]
Bueno, he empezado copiando un borrador que @cosmopaco ha incluido en el mensaje #2 ... a ver que os parece. 

G.

**Comment by cosmopaco** [comment]
Hola Guillen

La verdad es que me pasa lo mismo con github. Lo he probado hasta poniéndome bocabajo y no lo he entendido.
Ademas creo que github para windows tiene problemas con las configuración del proxy. Que por otro lado no se lo que es, ni me interesa averiguarlo en este momento.

Los manuales los puedes encontrar en los enlaces siguientes.
http://es.opendomo.org/odcontrol160
http://www.opendomo.com/wiki/index.php/Comandos_de_ODControl_v1.6.0

Voy un poco liado esta semana.!!!
Saludos.

**Comment by cosmopaco** [comment]
Os dejo un enlace de lo que he ido recopilando.
https://www.dropbox.com/s/2wz4wys9geu4l0f/ComandosDomino.doc
https://www.dropbox.com/s/4pngnovjcvrpy0o/ComandosDomino.odt

**Comment by cosmopaco** [comment]
Creo que tendríamos que usar el nuevo manual.
http://www.opendomo.com/wiki/index.php/Comandos_de_ODControl_v2.0.0

**Comment by cosmopaco** [comment]
He estrenado la wiki, 
No me gusta nada el aspecto, si alguien sabe como funciona que lo modifique!!!!!

**Comment by S3b4Bus0** [comment]
No esta nada mal la wiki. Es bueno que sea bien sencilla. No somos diseñadores graficos.. JA..
Deberiamos reunir la info repartida en diferentes lugares y concentrarla en esa wiki. Despues veo de agregar algo...

**Comment by cosmopaco** [comment]
Desatendido.
