### ISSUE TITLE
Problemas para conectarme al DOMINO

### ISSUE THREAD

**Issue by S3b4Bus0** [opalenzuela/dominoOSE#27]
Hola.. Me presento. Soy Sebastian de Argentina. Me sumo como Tester!! ja..
Estoy haciendo las primeras pruebas con un arduino MEGA + el shield Ethernet.

Resulta que puedo cargar el domino.ino en la placa, y la misma responde correctamente en la consola serial. Pero cuando ingreso algun comando me dice
E:board error 1

a que se puede deber?? tambien veo que no responde en la ip seteada.

gracias!!

**Comment by cosmopaco** [comment]
Hola Sebastian, bienvenido!!

Error 1 significa que el comando no es correcto.
Para iniciar Domino, se tiene que ingresar el comando "def". Con este comando haces que la Eeprom se cargue con la configuración por defecto.
Puedes verificar que todo este OK con el comando "lst" o "lsc".

Puede que te de error si no tienes bien configurada la consola serial.
Monitor serial configurado Velocidad  9600 y retorno de carro (Carriage return).

El tema dela ip es un poco lioso, si tu router tiene DHCP activado y una ip base diferente a 169.254.0.xxx  no le dará acceso a la red. Averigua cual es la ip de tu router y cámbiala manualmente al sketch Domino, 
<code>
byte defip[] = {169, 254, 0, 10 }; 
//cambiar 192.168.xx.x.
byte defip[] = {192, 168, 1, 10 }
</code>

Esta pendiente de corregir el comando "eth ip"
Puedes descargarte un borrador de los comandos de Domino, que se discuten en este issues.
https://github.com/opalenzuela/dominoOSE/issues/25

Saludos.

**Comment by S3b4Bus0** [comment]
Gracias Paco!! pude conectarme. Los sigo en el otro issue...
