### ISSUE TITLE
Compilar domino.ino en Linux

### ISSUE THREAD

**Issue by S3b4Bus0** [opalenzuela/dominoOSE#28]
Hola...  Alguien esta trabajando sobre linux??

Me dan los siguientes errores al intentar compilar, sin embargo la conexion serial funciona.

domino.ino:346:28: error: variable ‘strfmt_std_num’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:347:24: error: variable ‘strfmt_std’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:348:24: error: variable ‘strfmt_lnk’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:349:26: error: variable ‘strfmt_cmdok’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:350:26: error: variable ‘strfmt_error’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:354:25: error: variable ‘type_link’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:357:23: error: variable ‘str_upsec’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:358:23: error: variable ‘str_upday’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:360:23: error: variable ‘str_versn’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:361:23: error: variable ‘str_bdate’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:362:23: error: variable ‘str_build’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:364:23: error: variable ‘str_mfree’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:365:23: error: variable ‘str_mallo’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:366:23: error: variable ‘str_mused’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:368:23: error: variable ‘str_value’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:369:23: error: variable ‘str_empty’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:373:31: error: variable ‘str_http_header_1’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:374:31: error: variable ‘str_http_header_2’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:375:31: error: variable ‘str_http_header_3’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:376:31: error: variable ‘str_http_header_4’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:377:31: error: variable ‘str_http_header_5’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:378:31: error: variable ‘str_http_header_6’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:380:31: error: variable ‘str_http_footer_1’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
domino.ino:381:31: error: variable ‘str_http_footer_2’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’

Version de Framework Arduino 1:1.0.5+dfsg2-2

alguien tiene alguna idea?

**Comment by cosmopaco** [comment]
Que IDE de Arduino utilizas?
Vale lo la IDE 1.0.5 no la he probado!!!

**Comment by S3b4Bus0** [comment]
Es el IDE oficial, de la pagina http://arduino.cc. Lo probe sobre Debian y Ubuntu.

**Comment by cosmopaco** [comment]
Mira este enlace, es un problema de donde se debe poner la definición PROGMEN.
http://arduino.cc/es/Reference/PROGMEM#.UyL2ePl5Nb4

**Comment by S3b4Bus0** [comment]
Gracias por el dato Paco. Hice las modificaciones y pude compilar con la ultima version del compilador AVR.
Voy a ver su puedo generar el pull request.
