### ISSUE TITLE
Optimizar uso de memoria EEPROM

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/dominoOSE#3]
Actualmente, los puertos están ocupando "slots" de 20Bytes, dejando muy poco espacio disponible para puertos virtuales y enlaces. 

Se tratará de reducir el tamaño de estos "slots" a 16Bytes por puerto, para dejar más espacio disponible

**Comment by Shegar81** [comment]
Por mi lo encuentro correcto. Solo se trataría de ampliar los virtuales o los enlaces también?

**Comment by opalenzuela** [comment]
Los enlaces son muy potentes. Personalmente preferiría ampliar el número de enlaces antes que los virtuales, pero el objetivo ahora es reducir la cantidad de EEPROM usada para conseguir más espacio. Luego decidiremos como invertirlo.

**Comment by Shegar81** [comment]
Vale, me parece correcto paso a paso. Primero reducimos y luego en función de la reducción vemos como invertimos.
He visto que la versión base es la 1.1.3, en la web ponía que no se consideraba estable. En donde estaba la inestabilidad en donde trabajar. Yo no la instalé ne mi Arduino por esa razón, solo usé la 1.0

**Comment by opalenzuela** [comment]
En principio la versión 1.1.3 para Arduino es la más estable. Pero nos has avisado de un enlace erróneo de la página de descargas (que se correspondía a la 1.1.0, que esta sí era inestable)

**Comment by Shegar81** [comment]
Vale pues ahora la descargo al menos en uno de los Arduinos que tengo y la pongo en funcionamiento con el Opendomo2.0.
Como lo hago para descargarme la versión nueva que ya hemos modificado?

Saludos

**Comment by cosmopaco** [comment]
No se si te refieres a esta version?  https://www.dropbox.com/s/z6qyovjbrpwt70n/dominolnk_succes.ino
Lo siento pero no me deja subirla a Github. Me da error hay demasiadas diferencias. 
Seguiere intentadolo con cambios pequeños.

**Comment by Shegar81** [comment]
Acabo de copiar el domino.iso en el programa de arduino para exportarlo al MEGA y me ha dado los siguientes errores:
Domino1_1_4_ino.ino: In function 'int configPort(char, char_, char_)':
Domino1_1_4_ino:917: error: a function-definition is not allowed here before '{' token
Domino1_1_4_ino:2189: error: expected `}' at end of input
Creo que le están faltando cerrar algún corchete y por eso da el error. No tengo muy claro donde debería ir.

Saludos

César

**Comment by cosmopaco** [comment]
Donde esta esa versión?

**Comment by Shegar81** [comment]
HOla,

NO sé que he debido hacer mal pero algo seguro. Al postear he visto el post de cosmopaco una vez enviado ya el mio. He entrado me he descargado el del Dropbox y ya no da problema. Debe haber alguna cosa que no he hecho bien. 
De momento ya lo he cargado en el Arduino pero no consigo que se vea por la red.
Con la prueba del 1.1.3 se veía por la red pero el Opendomo2.0 no lo detecta

Saludos

**Comment by Shegar81** [comment]
Hola,

La he cogido de la vesión que hay en la carpeta SRC.

Saludos

**Comment by cosmopaco** [comment]
A mi no me da error al compilar?
El tema red no lo he probado.!!!!

**Comment by Shegar81** [comment]
Pues en red no sé porque no me acaba de funcionar. Pero algo he tocado porque en el de la 1.1.3 me funcionaba y al irlo configurando por la red se ha ido al traste

**Comment by cosmopaco** [comment]
Ojo tienen la misma ip. Entraran en conflicto.

**Comment by Shegar81** [comment]
les he cambiado las ip cada una tiene una diferente

**Comment by cosmopaco** [comment]
Reinicia los arduinos y la red. Las primeraz pruebas que hice me costo bastante ponerlos en la red.

**Comment by Shegar81** [comment]
Ya está resuleto el tema del 1.1.3 era una tontería. No podía estar conectado a través del puerto serie y a través de la ethernet a la vez. Es lógico pero cuando haces pruebas te despistas con cosas tontas así. 
No consigo la parte de red funcione en lo que pasaste

**Comment by cosmopaco** [comment]
No lo entiendo, no he cambiado nada de la parte de la red. Ya lo probaré.!

**Comment by Shegar81** [comment]
Lo siento he debido hacer algo mal y ahora me funciona corectamente con el tuyo. YO creo debe ser alguna cosa de números de serie o configuración parecida. Ya investigaré.
De momento lo dejo conectado para ver como responde a lo largo de los días.

**Comment by cosmopaco** [comment]
Perfecto, vamos avanzando.
Cuidado que yo soy novato en programación en C o C++.
La verdad es que gracias a este proyecto he aprendido alguna cosa.

**Comment by cosmopaco** [comment]
Creo que esta vez lo he subido correctamente. 

Ya tenemos espacio Eeprom de  sobras. Y los cambios de tamaño se pueden modificar sin gran esfuerzo.
Lo he testado varias veces y !!!FUNCIONA!!!!

**Comment by opalenzuela** [comment]
Genial! Cierro el Issue.

Queda uno más para saltar a la versión 1.1.4, a ver si lo conseguimos aislar.
