### ISSUE TITLE
Un voluntario para probar los cambios.

### ISSUE THREAD

**Issue by cosmopaco** [opalenzuela/dominoOSE#32]
Hola a todos.
Algún voluntario, puede probar los cambios.

Verificar los envíos por UDP y comunicación por Telnet.
Si encontráis algún  problema comentáis.

**Comment by S3b4Bus0** [comment]
Hola...
Hoy me pude poner a testearla.
El telnet funciona bien. Solo que luego de cada comando se desconecta. esta ok?
(estoy en linux, no probe en windows)

Con respecto a los UDP tambien funcionan perfecto. Solo envia cuando se actualiza un puerto. Con lo cual se refleja instantaneamente el cambio.

**Comment by cosmopaco** [comment]
Telnet se desconecta cuando envia la respuesta. No se el motivo exacto pero ya se escribio así.
El mayor problema era UDP, y con tus pruebas se reafirma que funciona.
Me generas una duda, donde ves reflejado el cambio?
Las pruebas que hice no actualizaban Opendomo OS.

**Comment by opalenzuela** [comment]
El motivo para desconectar después de cada petición es evitar que Domino se quede "enganchado" y que por tanto no pueda atender otras peticiones.

**Comment by S3b4Bus0** [comment]
Perdon, no, aun no estoy haciendo pruebas con Opendomo OS. Me referia que actualizaba la web del domino previa recarga, pero los paquetes UDP vi los vi con wireshark.

**Comment by S3b4Bus0** [comment]
ahora entiendo, opalenzuela....

(imagino ya se puede cerrar este issue)
