### ISSUE TITLE
Arduino MEGA

### ISSUE THREAD

**Issue by S3b4Bus0** [opalenzuela/dominoOSE#33]
Consulto, a todos los que tenemos un arduino Mega, que les parece crear y mantener un archivo diff, aplicable a domino.iso que lo adapten a este arduino??
con la ayuda de git es sencillo crear el diff

**Comment by S3b4Bus0** [comment]
Hola Shegar81, lei en algun issue que comentabas le habias agregado un watchdog, se puede publicar? podrias comentar como adaptaste el codigo de domino para utilizar todas las entradas/salidas del arduino mega??

gracias!

**Comment by cosmopaco** [comment]
Cuando tenga un rato, comento los problemas que veo para poder utilizar mas puertos y a la vez hacer compatible con Opendomo.

**Comment by opalenzuela** [comment]
Si no recuerdo mal, el SDK de Arduino incorpora variables de compilación (equivalentes a los #define de C) que se podrían utilizar para condicionar el comportamiento del código fuente. Será muy difícil mantener el código y los DIFF por separado a medida que el proyecto vaya sufriendo cambios...

**Comment by S3b4Bus0** [comment]
Ok, sugeri lo de los archivos diff porque parecia sencillo y para no
"ensuciar" todo lo hecho para el arduino ethernet. Pero si se hace con las
variables de compilacion quedaria mucho mejor. Voy a investigar un poco las
variables de compilacion para ver si puedo aportar algo, aunque igualmente
aun desconozco cuales serian los cambios necesarios para adaptarlo al mega

**Comment by cosmopaco** [comment]
Hola de nuevo.
Como os comentaba hay pequeños problemas para hacer que sea compatible, con las herramientas de configuración y trabajo que están basadas en ODControl. 

Hasta donde yo he podido entender, "que no es demasiado" ,tanto el configurador como Opendomo OS utilizan los comandos "lst" y"lsc" para determinar el estado y tipo de puerto. Hasta aquí no es un gran problema, pero si que me he fijado que en algunas funciones tratan los puertos por numero de orden.Sobre todos los analógicos que son del 16-23 en ODControl.
La numeración en ODC de los puertos físicos es la siguiente,  0-7 puertos salida digital (do), 8-15 puertos entradas digitales (di) 16-23 entradas analógicas (ai).
Todavía no se como tratan los (ao) y tampoco que pasaría si hubiera mas puertos físicos después del numero 23

En resumen, creo que solo seria posible configurar Domino como ODControl, tanto para arduino uno como para Mega.

Probablemente me equivoque en algún detalle!!! 
El maestro Oriol nos puede orientar...

**Comment by S3b4Bus0** [comment]
Hola!
No conocia esta "rigidez" en la identificacion de los puertos. La verdad que pense que era seteable la configuracion de puertos. Solo por esta vez, preferiria que estes equivocado... je!
A ver si el maestro nos ilumina en esto...

**Comment by opalenzuela** [comment]
Tenéis razón en apuntar a este problema de numeración "rígida" de los puertos, y de hecho hay un Issue en las herramientas de configuración que ya hace referencia a él:
https://github.com/opendomo/odcontrol/issues/28

Ésta es, de hecho, una de las principales diferencias entre Arduino y ODControl, ya que mientras ODControl tiene unos drivers de bajo nivel que hacen la traducción de los puertos físicos "reales" de la electrónica a una lista ordenada y correlativa de puertos usables, en Arduino, los puertos están siguiendo el mismo orden que en la placa, y parte de ellos quedan permanentemente deshabilitados al ser usados por la red y la SD.

En ese sentido, la solución "universal" sería emplear un indicador de tipo de puerto independientemente de su posición, de modo que sea posible expandir el listado para funcionar tanto con Mega como con Arduino Ethernet. Al mismo tiempo, modificar esas funciones para que en lugar de usar la posición usen ese indicador para identificar los tipos de puerto. Con ello vamos a consumir 1 Byte más de memoria por cada puerto, pero nos va a dar esa flexibilidad que nos falta.

**Comment by S3b4Bus0** [comment]
1 byte por puerto no parece un precio tan caro para la solución.. Seria bueno crear un issue para semejante funcionalidad.

**Comment by opalenzuela** [comment]
Buena idea. Hecho!

**Comment by cosmopaco** [comment]
Estoy trabajando en esto.

**Comment by S3b4Bus0** [comment]
OK. Avisen cualquier test que necesiten... :-)

**Comment by cosmopaco** [comment]
Hola 
Os dejo el enlace para el test.

https://www.dropbox.com/s/3m3y9bce93mfu3m/domino.ino

Teóricamente no tenéis que modificar nada, solo seleccionar vuestra tarjeta correctamente. 
Cargar el programa, por consola serial enviar el comando "def"

Si funciona correctamente tendréis 14 puertos digitales utilizables y 8 analógicos. Testar que funcionen correctamente las entradas y salidas.

Si todas las pruebas son correctas, se puede modificar el numero de puertos digitales y analógicos.
Para ello se tiene que modificar los valores. En el caso de Arduino Mega se encuentran a partir de la linea 244.
El numero de puertos digitales de entrada o salida son la mitad del valor de DIGITALPORTS, eliminándose los no utilizables.
<code>
#define DIGITALPORTS    16         //!< Number of digital ports
#define ANALOGPORTS     8           //!< Number of analog ports
#define VIRTUALPORTS    30  //!< Number of virtual ports
#define MAXLINKS    30                  //!< Number of links.
</code>

Saludos!!!!!

**Comment by S3b4Bus0** [comment]
Hola. Funciona! sin cambiar la cantidad de puertos.. pero cuando seteo DIGITALPORTS a 24 no funciona. Queda congelada la consola serie.
Como hago para entrar en algun modo debug como para ver que esta sucediendo?

**Comment by cosmopaco** [comment]
Sin cambiar nada cuantos puertos tienes de entrada y salida?
No hay ninguna herramienta de debug habilitada para eso.

**Comment by S3b4Bus0** [comment]
XX:di000:
XX:di001:
DI:di002:ON
DI:di003:ON
DI:di004:OFF
DI:di005:ON
DI:di006:ON
DI:di007:ON
DO:do008:ON
DO:do009:OFF
DO:do010:ON
DO:do011:OFF
DO:do012:OFF
DO:do013:OFF
DO:do014:OFF
DO:do015:ON
AI:ai000:+0253.0000
AI:ai001:+0024.0000
XX:ai002:
XX:ai003:
XX:ai004:
XX:ai005:
XX:ai006:

Esos son los puertos que aparecen, y los probe del 2 al 7 funcionan todos bien como entradas y del 8 al 15 como salidas.

**Comment by cosmopaco** [comment]
Al iniciar la consola serial aparece D: men y un valor.
Puedes indicarme el valor en los dos casos?
Otra cosa, en que pines conectas la tarjeta Ethernet?

**Comment by S3b4Bus0** [comment]
Te paso esos valores y la respuesta del comando mem

D:mem 6453
D:OK
I:.mfree  06375
I:.mallo  06362
I:.mused  00162

**Comment by Shegar81** [comment]
Los pines que utiliza para la comunicación con la Ethernet en el caso de la MEGA son directamente los ICSP que hay en el centro.

Para lo del Watchdog hay que implementar un bootloader diferente y después es incluir un par o tres de líneas en el código. No es complicado. Si buscas por internet hay documentación al rescpecto eso si en inglés.

**Comment by cosmopaco** [comment]
Memoria no parece que falte!!!!
De todas maneras puedes ir aumentando el numero de DIGITALPORTS haber hasta donde soporta?
El watchdog  no interesa ponerlo en este momento, tan solo reiniciaría el sistema.

**Comment by S3b4Bus0** [comment]
cuando le pongo 20 en DIGITALPORTS deja de responder...

**Comment by cosmopaco** [comment]
Que modelo  y revisión es tu Mega?
Se congela nada mas entrar en la consola serial o después de enviare el comando "def"?

**Comment by S3b4Bus0** [comment]
Mega 2560 R3

**Comment by cosmopaco** [comment]
Y cuando deja de funcionar, al entrar en monitor serial. Da alguna respuesta antes de congelarse?
Podrias probar solo ethernet y enviarle def?

**Comment by cosmopaco** [comment]
Cierro lo seguiremos #35

**Comment by rodrigozun** [comment]
como van con este proyecto estoy interesado... tienen el archivo beta???

**Comment by opalenzuela** [comment]
Lamento informarle que los proyectos de código abierto de OpenDomo Services han sido cerrados.
