### ISSUE TITLE
Identificar puertos por tipo y no por posición

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/dominoOSE#34]
Los puertos son identificados por su posición, lo que dificulta la adaptación del sketch para funcionar con Arduino Mega.

Sería conveniente modificar las configuraciones por defecto y las funciones que usan los tipos de puerto para poder seguir evolucionando.

**Comment by cosmopaco** [comment]
Si no hay otro remedio!!!!

Todo esto me parece un poco contradictorio. 
Por un lado tenemos unos puertos configurables por tipo y por otro la posición determina el tipo. Ahora queremos que el puerto tenga una posición dependiendo del tipo. 

Soy yo o esto esta muy rebuscado, carece de sentido.

No he leído bien el enunciado. 

<h2>
Identificar puertos por tipo y no por posición
</h2>

Creo que ya funciona así?

**Comment by S3b4Bus0** [comment]
Me encuentro analizando el codigo y aun no comprendo mucho como para aportar algo util. Igualmente, creo que lo que sugiere Oriol me parece lo mas correcto y escalable. Es muy limitado tener el tipo del puerto de acuerdo a su posicion. Agregando a cada puerto su tipo, se podria armar cualquier configuracion no solo para el arduino MEGA.

**Comment by cosmopaco** [comment]
Estamos un poco liados,,Jajajajj.

Esto solo es para los puertos físicos o reales.

Arduino tiene los pines digitales numerados.  0 a 13 en el caso de Uno y 0 a 53 en Mega 
Domino utiliza ese orden para determinar  "Port Id" indice del puerto. Podemos configurar cualquier  puerto como entrada o salida digital, incluso puedes decirle que se analógica de entrada. Como es lógico no funcionara el hardware es digital.

El problema es que ODControl si que tiene un orden preestablecido (lógico es hardware real) .
Las herramientas de configuración, en realidad no utilizan el Port Type que le entrega los comando "lst" o "lsc" para determinar el tipo de puerto. Utilizan en indice de puerto (numero, orden) para determinar el tipo de puerto.

**Comment by S3b4Bus0** [comment]
jajajaja.. no es un poco liado... estoy completamente liado...
Mirando el codigo veo que tienes razón. Actualmente esta asi.
Ahora la verdad que no entiendo la idea nueva...

**Comment by S3b4Bus0** [comment]
Pregunto entonces, el problema no estaria en las herramientas de configuración que no hacen uso del tipo y lo configuran por ubicacion?

**Comment by cosmopaco** [comment]
Exactamente.
El problema es que a ODControl no le puedes decir que el pin, puerto, indice...... llámalo como quieras. numero uno sea entrada, porque físicamente es una salida.

**Comment by Shegar81** [comment]
Yo creo que esto puede ser interesante pero primero hagamos que funcione el básico y después ya pasaremos a mayores. Esta bien poder tener más posibilidades pero demos un paso después de otro. Si ya de por si complicamos el tema nos costará identificar los problemas básicos que aún no tenemos reseltos. Mi opinión es centrarnos en que funcione y después si lo tenemos que replantear para ampliar posibilidades lo hacemos pero primero que funcione lo básico. Primero se suma y después cuando sabes sumar bien multiplicas.

**Comment by cosmopaco** [comment]
Creo que este issue se tiene que cerrar. Nadie tiene claro el problema y se esta  proponiendo algo que ya se hace.

**Comment by opalenzuela** [comment]
Viendo que se ha complicado la cosa, cierro este Issue para abrir otro más específico.
