### ISSUE TITLE
Acceso Remoto a Domino.

### ISSUE THREAD

**Issue by cosmopaco** [opalenzuela/dominoOSE#36]
Me parece muy interesante que podamos acceder a Domino fuera de nuestra instalación.
He estado buscando información y es posible, sin demasiada complicación. 

Lo que sería mas lógico es que los chicos de Opendomo, crearan en el servidor del cloud un pequeño programa que nos devuelva nuestra ip. En el formato mas sencillo posible para poner implementarlo en Domino.

**Comment by S3b4Bus0** [comment]
La verdad que no lo veo nada seguro acceder en forma remota a domino, Es mas, yo recomendaria se encuentren en una vlan separada a la red de pcs de la casa. Creo que lo ideal seria que en forma remota accedas a opendomo OS. Ademas, se puede instalar en opendomo algun cliente de dns dinamico (puede ser dyndns, o no-ip, etc)

**Comment by S3b4Bus0** [comment]
Vi por ahi, que habia un cliente android, pero no se si se conecta a opendomo, o a odcontrol. Seria interesante que lo haga tambien a opendomo..

**Comment by opalenzuela** [comment]
Estoy de acuerdo con @sebabuso . DominoOSE ni siquiera incorpora validación por HTTP Basic Auth, por lo que es un gran agujero de seguridad abrirlo. Además, el driver de red es muy vulnerable a ataques DoS.

ODControl dispone de cifrado y validación, pero incluso con todas estas capas de seguridad recomendamos acceder a él a través de un sistema principal (por ejemplo, OpenDomo OS)

**Comment by cosmopaco** [comment]
Es solo para jugar y para hacer que sea mas "atractivo".. 
Estamos de acuerdo que no es seguro, es mas  yo solo puedo asegurar una cosa. Aunque no lo haré, no es el lugar adecuado.

El producto profesional es y tiene que ser Opendomo con ODControl.

La lastima es que veo muy complicado comunicarlo con OpendomoOS y para que sea compatible con el configurador falta muchooooooo.....

**Comment by S3b4Bus0** [comment]
Es realmente complicado comunicar domino con opendomo OS?? pense que ya
estaba implementado y que solo no funcionaban algunas cosas menores.

El "famoso" configurador, donde se encuentra como para probar la
compatibilidad con domino? No tengo un odcontrol para hacer las pruebas. y
aqui en argentina dificilmente lo consiga. Por eso apuesto al Domino +
Opendomo OS

**Comment by cosmopaco** [comment]
Yo de momento no soy capaz de hacer que funcione Domino con OpendomoOS 2. Lo poco que he podido leer y entender hay cosas que no son equivalente con la estructura actual de Domino.

El configurador en realidad es javascript y se lo están escribiendo para ODControl 2. Mirate el issue #2 
http://cloud.opendomo.com/odctp/global1.6.3.js

**Comment by cosmopaco** [comment]
Peligro de "seguridad".
