### ISSUE TITLE
En ocasiones al resetear,  carga la configuración por defecto.

### ISSUE THREAD

**Issue by cosmopaco** [opalenzuela/dominoOSE#37]
He detectado que después de configurarlo alimentado a través de serial  y al cambiar la alimentación externa se carga la configuración por defecto.

Verificando en varias ocasiones. Los datos son correctos en Eeprom  y los puertos se setean correctamente solo cuando la alimentación es por el serial.

**Comment by opalenzuela** [comment]
Hay una característica que tal vez esté causando el problema:

```
pinMode(0,OUTPUT);
pinMode(1,INPUT);
digitalWrite(0, HIGH);
if (digitalRead(1)==HIGH)
{
    digitalWrite(0,LOW);
    if (digitalRead(1) == LOW) {
        eeprom_set_byte(EMBOARDOFFSET,255);
                    delay(5000);
    }
}
```

Esto es, si en el proceso de arranque los pines 0 y 1 están puenteados (o se están enviando y recibiendo los mismos datos) se produce un reset de la configuración. 

Esto se hizo para no depender del SDK a la hora de recuperar el dispositivo en caso de corrupción de memoria. En ODControl tenemos métodos más eficientes, pero para Arduino no quedaban demasiadas opciones.

**Comment by cosmopaco** [comment]
Tomo nota.
Ya lo habia detectado,  el pin 1 no esta polarizado.
Una pequeña señal hara que se cumplan las condiciones.

**Comment by opalenzuela** [comment]
¿Misterio resuelto? ¿Cierro el issue?

**Comment by opalenzuela** [comment]
Si no hay novedades al respecto, cierro este issue.
