### ISSUE TITLE
Unify link types

### ISSUE THREAD

**Issue by opalenzuela** [opalenzuela/dominoOSE#4]
Unify the link types with ODControl's. At least, direct, inverse, pulse, ..

**Comment by cosmopaco** [comment]
No son iguales?
Creo que pulse es diferente, perdón......

**Comment by opalenzuela** [comment]
Esos tres son iguales, pero posiblemente podamos incorporar algunos más.

**Comment by Shegar81** [comment]
Podríamos plantear ya directamente cual serían os siguientes

**Comment by opalenzuela** [comment]
Copio a continuación los tipos de enlaces existentes en la versión 1.6 de ODControl:
- d (directo) Si el puerto de entrada se pone a "on", el puerto de salida se pondrá también a "on". Entrada y salida siempre tendrán el mismo valor.
- i (inverso) Si el puerto de entrada se pone a "on" el de salida se pone a "off". Entrada y salida siempre tendrán valores opuestos.
- p (pulso) Si se recibe un pulso en la entrada (off -> on -> off) el puerto de salida cambiará de valor. Si está en "on" pasará "off" y viceversa.
- 2 (Multitap de doble pulso) Si se reciben dos pulsos consecutivos en la entrada el puerto de salida cambiará de valor. Si está en "on" pasaá a "off" y viceversa.
- 3 (Multitap de triple pulso) Si se reciben tres pulsos consecutivos en la entrada el puerto de salida cambiará de valor. Si está en "on" pasaá a "off" y viceversa.
- l (Pulsación larga) Regula una variable analogica segun el tiempo se mantenga pulsado el pulsador.
- c (conmutado o cambio) Si se realiza un cambio en el puerto de entrada (on -> off, off -> on) el puerto de salida cambiará de valor independientemente de su estado actual (on, off). Si está en "on" pasará "off" y viceversa. Entrada y salida no tienen porqué tener el mismo valor
- r (retorno) Si el puerto de entrada cambia de valor, el puerto de salida se pone a "on" y después regresa a su estado "off", generando un pulso de unos 500ms.
- t (retorno en subida) Si el puerto de entrada se pone a "on", el puerto de salida se pone a "on" y después a "off", generando un pulso, igual que el enlace de tipo r.
- s (self, reflexivo) Si el puerto de entrada se pone a "off", el puerto de salida se pone a "on" y después a "off" (pulso). Si el puerto de entrada se pone a "on", el puerto de salida se pone a "off". Se utiliza para crear un enlace con un mismo puerto origen y destino, con el objetivo de que siempre que cambie vuelva a "off" (ej: lnk do000 do000 s).
- b (boot o arranque) Enlace que se aplica únicamente al reiniciar el odcontrol. Se utiliza para establecer un valor de inicialización. Por ejemplo, para que siempre que se reinicie ODControl un puerto do000 quede a "on" haríamos "lnk btrue do000 b". Donde btrue es un puerto virtual de tipo "val" establecido a 1.
- k (interlock o interbloqueo) Asocia dos puertos de manera que nunca puedan ponerse ambos a "on". En ese caso, si se intenta poner uno de los puertos a "on" el otro se pondría automáticamente a "off". Solo puede usarse en puertos digitales.
- n (contador de pulsos) Este enlace vincula un puerto digital con un puerto analógico virtual, de modo que cada vez que el puerto digital pase de "on" a "off", se incrementará en una unidad el puerto de destino.
- N (contador de pulsos inverso) Idéntico al enlace n, pero contando únicamente del paso de "off" a "on".

A mi entender, los más importantes son: d, i, p (ya existentes) y c, r, n. Los multitap son complejos de implementar, y otros pueden crearse mediante la combinación de un inverso con otro de los básicos.

**Comment by cosmopaco** [comment]
Le he estado dando vueltas a los enlaces multitap.
Y no acabo de entender p (pulse) también esta retardado como 2 y 3 ?
Si no es así no entiendo como hacerlo.

**Comment by Shegar81** [comment]
La I no acabo de ver como se realizaría con el resto, pero entiendo que lo tienes claro. Por el resto penso que tienes razón Oriol.

**Comment by opalenzuela** [comment]
Implementar el tipo de enlace "l (largo)" es muy complejo. Es por esa razón que lo descartaría para la versión de Arduino. Lo mismo sucede con los multitap.

**Comment by cosmopaco** [comment]
Estoy trabajando con los enlaces y me esta trastornado el sueño. Estoy acostumbrado a autómatas programables y algunas cosas me parecen el mundo al revés.

Espero explicarme correctamente y vuestra respuesta.

1º¿ Entiendo que una entrada se visualiza On cuando esta a HIGH, osea sin puentear a negativo? 
    Si ODControl trabaja de esta manera lo acepto, aunque me rompe mi lógica habitual.

2º¿Los enlaces solo pueden se entre un puerto de entrada y un puerto de salida? 
   Si es así, no entiendo porque no pueden ser entre dos salidas. Ademas el tipo k (interlock o interbloqueo) no se puede realizar al menos que sea una excepción.

3º ¿Los enlaces directos e indirectos son realmente lo que indican?
  Como se ejecutan actualmente no lo son. Mas bien son puertos (flanco de subida=>set) (flanco de bajada=>reset).
  Por otro lado si fueran realmente directo no se podría cambiar el estado remotamente!!!
4º ¿Es necesario mantener la anulación de un puerto cuando se producen muchos cambios?
    En la funcion refreshPortStatus() se ejecuta if (ports[i].changes >= MAXCHANGES) anula totalmente el puerto y nunca mas vuelve a su estado de configuración.
5º ¿Es posible que con el orden actual de ejecución de las lecturas y refresco de cambios en ocasiones se pierda un flanco?

**Comment by opalenzuela** [comment]
Intentaré solucionar estas dudas brevemente.
1. Correcto. HIGH=12V=ON Piensa en una lámpara controlada por un relé conectado al puerto. La lámpara está en ON cuando el relé está excitado, por tanto cuando por el puerto circula corriente, por tanto cuando está en HIGH
2. En ODControl es posible enlazar desde cualquier puerto a uno virtual o de salida. Esto significa que una salida puede enlazarse con otra salida, una entrada con una salida, pero NUNCA una entrada con otra entrada o una salida con una entrada.
3. En ODControl si lo son, pero en Domino está muy simplificado (por limitaciones de espacio)
4. Si no lo hacemos cualquier puerto de entrada que no esté conectado a ningún sitio (alta impedancia) mantendrá el sketch demasiado ocupado de forma inútil. 
5. Si el flanco es menor que el tiempo de lectura, sí. Aunque esto nos sirve también para descartar  ruido en los sensores. A veces, cuando se activa una carga capacitiva fuera del circuito se generan pulsos inducidos en él; estos pulsos son muy breves, pero antes de tener esta limitación generaban situaciones imprevistas. A la práctica no representa un problema en la mayoría de situaciones. Actuar de forma manual sobre un pulsador durante menos de 100ms es poco frecuente.

**Comment by cosmopaco** [comment]
Gracias Oriol.
Aunque en la pregunta uno no me he explicado bien, me refría a una entrada. 
En automatismos cualquier tipo de panel indicador sea electromecánico, pantalla,HMI o  Scada, una entrada se visualiza como ON, con un piloto o un símbolo que indica activo, en el caso que este puenteado con el común de la entrada y puede ser un interruptor o pulsador luminoso.

En  Domino es al contrario, indicamos ON  cuando no tenemos nada conectado, aunque  si que es cierto que la entrada esta en estado HIGH por la resistencias de polarización.
Un ejemplo claro seria, conectar un interruptor estándar, contacto  tipo N.O. lo ponemos en la posición ON con lo cual puente la entrada al común. Domino lo trata e indica como OFF, ya que la entrada esta en LOW.

Otro tema son las salidas, normalmente se indican son un piloto o símbolo y no se puede interactuar con ellas. De ahí el desconcierto de Shegar81 ( Cesar?)  al ver la representación web, las entradas como pilotos y las salidas como interruptores.

De todas formas si hasta ahora se ha hecho así no hay motivos para cambiarlo.
Saludos.

**Comment by opalenzuela** [comment]
Ahora entiendo. Lo hacemos así por las características de la placa de Arduino, muy a nuestro pesar. De este modo es posible cargar el sketch cuando no hay nada conectado a la placa, sin que éste se vuelva loco. De hecho, en las primeras versiones iba al revés, pero tuvimos que cambiarlo para conseguir algo estable.

Aunque sea poco intuitivo al principio para los que venís del sector industrial, es fácil de entender para los usuarios que no disponen de conocimientos de electricidad de potencia. Si ven un interruptor saben directamente que pueden actuar sobre él (como las salidas) y si ven un piloto, saben que es solamente para mirar.

En cualquier caso, el objetivo es que el sketch sea lo más compatible posible con ODControl, para que así podamos empezar a compartir recursos (documentación, herramientas de configuración, etc) y poder usarlos como entrenadores. Falta bastante poco para que esto suceda!

**Comment by cosmopaco** [comment]
Tengo el código generado con muchos de los enlaces, estoy en pruebas. 
Hay un error que se resiste, tengo que depurar.
Saludos.

**Comment by opalenzuela** [comment]
Corregido en el último pull.
