### ISSUE TITLE
Representación en formato web

### ISSUE THREAD

**Issue by Shegar81** [opalenzuela/dominoOSE#9]
Hola,

Después de estar probando las mejoras me encuentro con dos situaciones.
La representación de las entradas y las salidas digitales en formato web se encuentran giradas. Me explico la representación de las entradas digitales se muestran como un led y las de las salidas como un interruptor. Es esto correcto para mi sería a la inversa. Si es que estoy equivocado me podríais corregir y explicar el sentido?

Saludos

**Comment by cosmopaco** [comment]
La primera vez que vi la interface dr Domino me hice esa misma pregunta..Jajjaja.
Las entradas se visualizan con su estado activa, desactiva o valor numerico en el caso de las analogicas. Las puertos digitales salida son los que podemos cambiar de estado. En el caso de los digitales se representan con el interruptor,al pulsar sobre el interruptor"forzamos" que cambien de estado.
De momento los puertos de salida analógicos no se puede modificar su valor.

También te tengo que decir que la web es estática, solo se actualiza si pulsamos sobre un interruptor o recargamos la web.

El tema de que lo reconozca Opendomo, no tengo ni idea. No se si lo ha reconocido en las primeras versiones y se ha eliminado posteriormente.
Saludos.

**Comment by opalenzuela** [comment]
Doy por cerrado este issue, ya que se ha discutido en otro apartado.
